sudo: required
services:
  - docker

before_install:
  - docker build -t sergiopoliveira/docker-react -f Dockerfile.dev .

script: 
  - docker run sergiopoliveira/docker-react npm run test -- --coverage

# deploy to AWS
#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: docker
#  env: "Docker-env"
#  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#  bucket-path: "docker"
#    on:
#      branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key:
#      secure: "AWS_SECRET_KEY"

# aws IAM (manage API keys)
# Users -> Add User (docker-react-travis-ci), Programmatic access