sudo: required
services:
  - docker

before_install:
  - docker build -t sergiopoliveira/docker-react -f Dockerfile.dev .

script: 
  - docker run sergiopoliveira/docker-react npm run test -- --coverage